name: Nightly Match
on:
  workflow_dispatch:
jobs:
  match:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: echo "workflow alive"
